service: auction-service

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

  environment:
    AUCTIONS_TABLE_NAME: AuctionsTable-${self:provider.stage}

  iamRoleStatements:
    - ${file(./iam/AuctionsTableIAM.yml)}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
  
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
  
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: patch
          path: /auction/{id}/bid
  

resources:
  Resources:
    AuctionsTable: ${file(./resources/AuctionsTable.yml):AuctionsTable}
